### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by negreanucalin** [applitools/jest-environment-selenium#5]
After installing and configuring the project and running: yarn test an error is thrown:

>  Plugin/Preset files are not allowed to export objects, only functions. In /home/cnegreanu/Documents/devenv/projects/testing-e2e-2/node_modules/babel-preset-node6/index.js

**Comment by corevo** [comment]
Can you share your `package.json`?, it seems weird since this package has no production dependencies.

**Comment by negreanucalin** [comment]
So sorry, I must have changed some dependency by mistake.
Thank you, have a nice day
